# Generated by Django 3.2.13 on 2022-10-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('content', models.TextField()),
                ('create_at', models.TimeField(auto_now_add=True)),
                ('update_at', models.TimeField(auto_now=True)),
            ],
        ),
    ]
